### ISSUE TITLE
댓글 작성 api 연결 안됨

### ISSUE THREAD

**Issue by kanghohyeong** [boostcampwm-2021/web20-PingPingsFriends#260]

**Comment by ludacirs** [comment]
`getAuthOption` 함수의 `body` 파라미터로 json으로 안 쏘고 객체로 바로 쏘고 있어서 못 받은거였네요!

`JSON.stringify()`로 묶고 `Content-Type`까지 설정해주니까 잘 들어갑니다

제가 고쳐서 PR 날릴게요!

![image](https://user-images.githubusercontent.com/45571631/143680143-95fe4fd2-b74c-4b3a-bee3-6c3edf9a8bf6.png)

![image](https://user-images.githubusercontent.com/45571631/143680125-b6802d67-8be5-489c-b086-2ad15184a61b.png)
