### ISSUE TITLE
프로필 편집 API 이슈

### ISSUE THREAD

**Issue by ludacirs** [boostcampwm-2021/web20-PingPingsFriends#270]
## 상황

1. 프론트에서 보내도, 스웨거로 테스트를 해도 500에러 반환,

2. 이걸 고치고 나서도 어떤 아이디로 로그인 해도 userId값이 1인 유저의 이미지 프로필을 변경하는 이슈 발생

3. 이걸 고치고 나서도 -profile 이 붙어서 url이 DB에 저장됨

## 이미지

- 반환값

![image](https://user-images.githubusercontent.com/45571631/143730644-7672df83-f9c0-4c9a-b8de-2a034eb038ba.png)

- nest 로그
 
![image](https://user-images.githubusercontent.com/45571631/143730638-34f0e0b5-db72-406e-980e-e974a3b5d9a6.png)

## 원인

1. 요청으로 받은 image 파일을 파싱 않고 그대로 써서 url값에 제대로 접근할 수 없었음
    - 만들어 둔 `getPartialFileInfo`을 사용해서 해결
2. `userId`값으로 찾는 쿼리에 `undefined`가 들어가고 있었음
    - 왜 에러가 발생하지않고 1번 유저를 찾는지 궁금
3. DB에 저장된 파일명에 -profile이 붙어서 저장
    - 일단 하드코딩해놨는데 제가 잘못짠건지 지금 문제가 있는지 확인 부탁드립니다

**Comment by 9b2n** [comment]
요청 객체도 어떻게 보내는 지 보여주면 좋을 것 같아요

**Comment by ludacirs** [comment]
아 이거는 다 수정해서 PR올려놨어요

**Comment by ludacirs** [comment]
https://github.com/boostcampwm-2021/web20-PingPingsFriends/pull/267/commits/ff119910d939f566e6bff05b92eee6d450ff1c12

보고 이상한 부분 있으면 리뷰 부탁드립니다.. 다른 부분 보고 카카시해서 수정한거라 ㅋㅋㅋ
